{{- if eq (include "generic.workloadType" .) "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- include "generic.renderAnnotations" (dict "global" . "local" nil) | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  {{- with .Values.workload.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "generic.podLabels" . | nindent 8 }}
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "generic.podSpec" . | nindent 6 }}
{{- end }}
