{{- if eq (include "generic.workloadType" .) "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- include "generic.renderAnnotations" (dict "global" . "local" nil) | nindent 2 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  {{- with .Values.workload.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.workload.deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.workload.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "generic.podLabels" . | nindent 8 }}
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "generic.podSpec" . | nindent 6 }}
{{- end }}
