{{- if .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- include "generic.renderAnnotations" (dict "global" . "local" nil) | nindent 2 }}
stringData:
  {{- include "generic.secretData" (dict "files" .Values.secretFiles "context" $) | nindent 2 }}
{{- end }}
{{- if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret-env
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- include "generic.renderAnnotations" (dict "global" . "local" nil) | nindent 2 }}
stringData:
  {{- range .Values.secretEnv }}
  {{- if not (and (hasKey . "name") (hasKey . "value")) }}
  {{- fail "secretEnv entries require both 'name' and 'value' keys" }}
  {{- end }}
  {{ .name }}: {{ include "generic.tplValue" (dict "value" .value "context" $) | quote }}
  {{- end }}
{{- end }}
