{{- if .Values.mountSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret-mount
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  {{- include "generic.config.configmap" (dict "context" $ "value" .Values.mountSecret ) | nindent 2 }}
{{- end }}
{{- if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret-env
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  {{- $global := $ }}
  {{- range $secret := .Values.secretEnv }}
    {{- if or (not (hasKey $secret "name" )) (not (hasKey $secret "value")) }}
      {{- fail "secretEnv entries require both a 'name' and a 'value' key" }}
    {{- end }}
  {{ get $secret "name" }}: {{ include "generic.tplvalues.render" (dict "value" (get $secret "value") "context" $global) | trim | quote }}
  {{- end }}
{{- end }}
